---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: torreviejawireless.org
  namespace: tw
spec:
  secretName: tw-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt

  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - "torreviejawireless.org"
    - "*.torreviejawireless.org"
