---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vseva-remote
  labels:
    org.democratic-csi.manual: vseva-remote
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: vseva-remote
    volumeAttributes:
      server: 192.168.4.5
      share: /mnt/main/home/vseva
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config
  namespace: tw
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vseva-remote
  namespace: tw
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      org.democratic-csi.manual: vseva-remote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: code-server
  name: code-server
  namespace: tw
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: code-server
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Madrid
            - name: PROXY_DOMAIN
              value: coder.torreviejawireless.org
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server
                  key: PASSWORD
            - name: SUDO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server
                  key: SUDO_PASSWORD
          image: lscr.io/linuxserver/code-server:latest
          name: code-server
          ports:
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: code-server-config
            - mountPath: /config/workspace
              name: code-server-workspace
              subPath: workspace
      restartPolicy: Always
      volumes:
        - name: code-server-config
          persistentVolumeClaim:
            claimName: code-server-config
        - name: code-server-workspace
          persistentVolumeClaim:
            claimName: vseva-remote
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: code-server
  name: code-server
  namespace: tw
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8443
  type: ClusterIP
  selector:
    io.kompose.service: code-server
