---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitea-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://dl.gitea.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 30m
  releaseName: gitea
  targetNamespace: tw
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: gitea
      version: "7.0.x"
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 12h
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    nodeSelector:
      kubernetes.io/arch: amd64
    global:
      storageClass: freenas-iscsi-csi
    postgresql:
      enabled: true
      image:
        tag: 15.2.0-debian-11-r11
    memcached:
      enabled: true
      image:
        tag: 1.6.19-debian-11-r0
    service:
      ssh:
        type: LoadBalancer
        externalTrafficPolicy: Local
        port: 2223
        annotations:
          metallb.universe.tf/address-pool: external-pool
          metallb.universe.tf/loadBalancerIPs: 192.168.5.243
    image:
      rootless: true
    gitea:
      admin:
        existingSecret: gitea-admin-secret
        email: victor.seva+gitea@gmail.com
      config:
        server:
          ROOT_URL: https://git.torreviejawireless.org/
          DOMAIN: git.torreviejawireless.org
          START_SSH_SERVER: true
          SSH_PORT: 2223
        service:
          DISABLE_REGISTRATION: true
      persistence:
        enabled: true
        storageClass: freenas-iscsi-csi
