---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 30m
  releaseName: jenkins
  targetNamespace: jenkins
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: jenkins
      version: "12.0.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    global:
      storageClass: freenas-iscsi-csi
    nodeSelector:
      kubernetes.io/arch: amd64
    jenkinsUser: vseva
    jenkinsHost: jenkins.torreviejawireless.org
    agentListenerService:
      enabled: true
      # this is needed in order make it work, jenkins URL ==>
      # http://jenkins-agent-listener.jenkins.svc.cluster.local
      extraPorts:
        - name: http
          protocol: TCP
          port: 80
          targetPort: http
    agent:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/jenkins-inbound-agent
        tag: latest
        pullPolicy: Always
    plugins:
      - kubernetes:3900.va_dce992317b_4
    extraPlugins: []
    overridePlugins: true
    rbac:
      create: true
      rules:
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
        - apiGroups: [""]
          resources: ["pods/exec"]
          verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
        - apiGroups: [""]
          resources: ["pods/log"]
          verbs: ["get", "list", "watch"]
        - apiGroups: [""]
          resources: ["events"]
          verbs: ["watch"]
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["get"]
    serviceAccount:
      create: true
      automountServiceAccountToken: true
