---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 24h
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 30m
  releaseName: nextcloud
  targetNamespace: tw
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: nextcloud
      version: "3.5.x"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 12h
  values:
    global:
      postgresql:
        auth:
          password: reallysecret
    image:
      flavor: fpm
    nginx:
      enabled: true
    nextcloud:
      host: cloud.torreviejawireless.org
      existingSecret:
        enabled: true
        secretName: nextcloud
        mail:
          enabled: true
          fromAddress: noreply@torreviejawireless.org
          domain: torreviejawireless.org
          smtp:
            host: mailu-postfix.tw.svc.cluster.local
            secure: ssl
            port: 465
            authtype: LOGIN
    internalDatabase:
      enabled: false
    postgresql:
      enabled: true
      image:
        tag: 15.2.0-debian-11-r11
      primary:
        persistence:
          enabled: true
          storageClass: freenas-iscsi-csi
    persistence:
      enabled: true
      storageClass: freenas-iscsi-csi
      nextcloudData:
        enabled: true
        storageClass: freenas-iscsi-csi
    phpClientHttpsFix:
      enabled: true
    rbac:
      enabled: true
    cronjob:
      enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd
      tls:
        - secretName: tw-tls
          hosts:
            - cloud.torreviejawireless.org
