---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: tw
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.5.240
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app.kubernetes.io/name: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: tw
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.4.240
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app.kubernetes.io/name: nextcloud
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-http
  namespace: tw
spec:
  redirectScheme:
    scheme: https
    permanent: true
