---
global:
  defaultStorageClass: freenas-iscsi-csi
  security:
    allowInsecureImages: true
nodeSelector:
  kubernetes.io/arch: amd64
postgresql-ha:
  enabled: false
postgresql:
  auth:
    password:
    postgresPassword:
  enabled: true
  image:
    tag: 17.4.0-debian-12-r2
    registry: bitnamilegacy
  primary:
    persistence:
      enabled: true
      selector:
        matchLabels:
          app: tw-gitea-pg
    initContainers:
      - image: pgautoupgrade/pgautoupgrade:17-trixie
        name: upgrade-postgres
        securityContext:
          runAsUser: 0
        env:
          - name: PGAUTO_ONESHOT
            value: 'yes'
          - name: POSTGRES_DB
            value: gitea
          - name: PGDATA
            value: /bitnami/postgresql/data
          - name: POSTGRES_PASSWORD
            value: whatever
        volumeMounts:
          - mountPath: /bitnami/postgresql
            name: data
redis-cluster:
  enabled: false
redis:
  enabled: true
  architecture: standalone
  image:
    registry: bitnamilegacy
  global:
    redis:
      password:
  master:
    count: 1
service:
  ssh:
    type: LoadBalancer
    externalTrafficPolicy: Local
    port: 2223
    annotations:
      metallb.io/address-pool: external-pool
      metallb.io/loadBalancerIPs: 192.168.5.243
image:
  rootless: true
gitea:
  admin:
    existingSecret: gitea-admin-secret
    email: victor.seva+gitea@gmail.com
  config:
    server:
      ROOT_URL: https://git.torreviejawireless.org/
      DOMAIN: git.torreviejawireless.org
      START_SSH_SERVER: true
      SSH_LISTEN_PORT: 2223
    service:
      DISABLE_REGISTRATION: true
persistence:
  enabled: true
  create: false
  claimName: gitea-data
  mount: true
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd
  hosts:
    - host: git.torreviejawireless.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tw-tls
      hosts:
        - git.torreviejawireless.org
