---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitea-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://dl.gitea.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  dependsOn:
    - name: tw-memcached
  interval: 30m
  releaseName: gitea
  targetNamespace: tw
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: gitea
      version: 10.4.x
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: gitea-values
      valuesKey: values-gitea.yaml
    - kind: Secret
      name: gitea-config
