---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/sops: enabled
resources:
  - images.yaml
  - certificate.yaml
  - traefik.yaml
  - storage.yaml
  - memcached.yaml
  - nextcloud.yaml
  - gitea.yaml
  - quassel.yaml
  - freshrss.yaml
secretGenerator:
  - name: nextcloud-config
    namespace: flux-system
    files:
      - values.yaml=secret-values.enc.yaml
  - name: gitea-config
    namespace: flux-system
    files:
      - values.yaml=gitea-secret-values.enc.yaml
configMapGenerator:
  - name: nextcloud-values
    namespace: flux-system
    files:
      - values-nextcloud.yaml=values.yaml
  - name: gitea-values
    namespace: flux-system
    files:
      - values-gitea.yaml=gitea-values.yaml
configurations:
  - kustomizeconfig.yaml
