---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tw-memcached
  namespace: flux-system
spec:
  interval: 30m
  releaseName: memcached
  targetNamespace: tw
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: memcached
      version: 6.7.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    architecture: standalone
    auth:
      enabled: false
    persistence:
      enabled: false
