---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 24h
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  dependsOn:
    - name: tw-memcached
  interval: 30m
  releaseName: nextcloud
  targetNamespace: tw
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: nextcloud
      version: 8.1.x
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: nextcloud-values
      valuesKey: values-nextcloud.yaml
    - kind: Secret
      name: nextcloud-config
