---
## secrets values
global:
  postgresql:
    auth:
      postgresPassword:
      password:
##
image:
  flavor: fpm
nginx:
  enabled: true
nextcloud:
  host: cloud.torreviejawireless.org
  existingSecret:
    enabled: true
    secretName: nextcloud
    mail:
      enabled: false
  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '127.0.0.1',
          1 => '10.0.0.0/8',
        ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
      );
internalDatabase:
  enabled: false
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      selector:
        matchLabels:
          app: tw-nextcloud-pg
persistence:
  enabled: true
  existingClaim: nextcloud
  nextcloudData:
    existingClaim: nextcloud-data
    enabled: true
phpClientHttpsFix:
  enabled: true
rbac:
  enabled: true
cronjob:
  enabled: true
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd
  tls:
    - secretName: tw-tls
      hosts:
        - cloud.torreviejawireless.org
