---
apiVersion: v1
kind: Secret
metadata:
  name: wp-mariadb
  namespace: sipwork
stringData:
  mariadb-password: ENC[AES256_GCM,data:/72+hRa4vYn5gAMLyH7tow==,iv:UIIciIqgWOdMIw0f0BhTi5B935lga5B7pQuaZwE7J6I=,tag:AcP7UGbAEhg4MHk6e1Wf/w==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:GFQQgI+xfs8Sxn6Eq6ezuw==,iv:/tyW6JKwmYcLztLVV8+pIkmHRieCF3hRIxCIyauVoYg=,tag:uI9C9NPAX4lJuERoR9WCzQ==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb25qTU1vTFg1SzFVcGRa
        OUNnekZnSFpGd0tpUW50MXhtTGZrdE1saEJvCnV4ZmZPUUJTbVR6anJpaGwzYVdw
        L3c4cExLNjZEUlBBckVFMUllNTdaNDgKLS0tIHF6S1JuMUxwY3E2QnQ3cmFYRGh6
        dnVMQWNmL01RbFl4amF5REFiRGcxRncK3ej4HvcWvioFibIlBV9jrAFBEqJYb4+1
        Az8MKmyqmWD1f3QHWvaccjoqkpIg/dfVavr9ccRjXoHWSzhXRqFZkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-10-18T13:29:07Z'
  mac: ENC[AES256_GCM,data:CsYYh1kjmc6sA/7M5uWIjBWFBdA23sb9QUb62sm4n1p3JvlZTHIhJ+BdJk2eWNWzk91pN/Dylx+n79+lbrLSlY+fkvYGC4rjUzQf97YE/9hnw/2P65bq8bB5PpAUdKxk/nG4+JTepwv6Y0bOeNpCedUvLcem1KF+wwFfNMb0Fy8=,iv:P1mIAfFNSrow0PJfI4xPULGBqK3kqBA8NapNzywnz3s=,tag:7boqIQHjm/YVL9LeDd3NIA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
