---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  name: 00d03114-0000-0000-0000-e45f0135fb38
  labels:
    metal.sidero.dev/serverclass: rpi.8gb
    metal.sidero.dev/machine.type: worker
spec:
  accepted: true
  hostname: k3s-node2.lab
  pxeBootAlways: true
  environmentRef:
    namespace: default
    name: rpi4
  hardware:
    system:
      # 2374c917
      manufacturer: Raspberry Pi Foundation
      productName: Raspberry Pi 4 Model B
      version: D03114
      serialNumber: 0000E45F0135FB38
  configPatches:
    - op: add
      path: /machine/network
      value:
        interfaces:
          - deviceSelector:
              hardwareAddr: e4:5f:01:35:fb:38
            dhcp: true
    - op: replace
      path: /machine/install/disk
      value: /dev/mmcblk0
    - op: add
      path: /machine/sysctls
      value:
        kernel.kexec_load_disabled: 1
