---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  name: 00d03114-0000-0000-0000-e45f01496eb7
  labels:
    metal.sidero.dev/serverclass: rpi.8gb
    metal.sidero.dev/machine.type: controlplane
spec:
  accepted: true
  hostname: k3s-node1.lab
  pxeBootAlways: true
  environmentRef:
    namespace: default
    name: rpi4
  hardware:
    system:
      # ae88c0f7
      manufacturer: Raspberry Pi Foundation
      productName: Raspberry Pi 4 Model B
      version: D03114
      serialNumber: 0000E45F01496EB7
  configPatches:
    - op: add
      path: /machine/network
      value:
        interfaces:
          - deviceSelector:
              hardwareAddr: e4:5f:01:49:6e:b7
            dhcp: true
            vip:
              ip: 192.168.4.201
    - op: replace
      path: /machine/install/disk
      value: /dev/mmcblk0
    - op: add
      path: /machine/sysctls
      value:
        kernel.kexec_load_disabled: 1
