---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  name: f6ab382a-171c-11ee-9a2d-f3300775a202
  labels:
    metal.sidero.dev/serverclass: trigkey
    metal.sidero.dev/machine.type: worker
spec:
  accepted: true
  hostname: k3s-node5.lab
  hardware:
    compute:
      processors:
        - manufacturer: Advanced Micro Devices, Inc.
          productName: AMD Ryzen 5 5560U with Radeon Graphics
    system:
      family: Default string
      manufacturer: AZW
      productName: S5
      serialNumber: Default string
      skuNumber: Default string
      version: Default string
  pxeBootAlways: true
  environmentRef:
    namespace: default
    name: amd64
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: add
      path: /machine/network
      value:
        interfaces:
          - deviceSelector:
              hardwareAddr: b0:41:6f:09:e6:60
            dhcp: true
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
    - op: add
      path: /machine/install/extraKernelArgs
      value:
        - console=ttyUSB0,115200
    - op: add
      path: /machine/install/extensions
      value:
        - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:3ab305068aa28513b26ab3c5b1f2937dbe3f63b9c50abe290287cc58eb454bb9
        - image: ghcr.io/siderolabs/amd-ucode:20230804
        - image: ghcr.io/siderolabs/amdgpu-firmware:20230804
