---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  name: 00d03114-0000-0000-0000-e45f01496f26
  labels:
    metal.sidero.dev/serverclass: rpi.8gb
    metal.sidero.dev/machine.type: controlplane
spec:
  accepted: true
  hostname: k3s-master.lab
  pxeBootAlways: true
  environmentRef:
    namespace: default
    name: rpi4
  hardware:
    system:
      # 32fc0ab3
      manufacturer: Raspberry Pi Foundation
      productName: Raspberry Pi 4 Model B
      version: D03114
      serialNumber: 0000E45F01496F26
  configPatches:
    - op: add
      path: /machine/network
      value:
        interfaces:
          - deviceSelector:
              hardwareAddr: e4:5f:01:49:6f:26
            dhcp: true
            vip:
              ip: 192.168.4.201
