---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  name: 03000200-0400-0500-0006-000700080009
  labels:
    metal.sidero.dev/serverclass: trigkey
    metal.sidero.dev/machine.type: worker
spec:
  accepted: true
  hostname: k3s-node3.lab
  hardware:
    compute:
      processors:
        - manufacturer: Advanced Micro Devices, Inc.
          productName: AMD Ryzen 5 5560U with Radeon Graphics
    system:
      family: Default string
      manufacturer: AZW
      productName: S5
      serialNumber: Default string
      skuNumber: Default string
      version: Default string
  pxeBootAlways: true
  environmentRef:
    namespace: default
    name: amd64
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: add
      path: /machine/network
      value:
        interfaces:
          - deviceSelector:
              hardwareAddr: b0:41:6f:08:39:95
            dhcp: true
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
