---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  name: 031b021c-040d-05f9-bd06-900700080009
  labels:
    metal.sidero.dev/serverclass: gigabyte
    metal.sidero.dev/machine.type: worker
spec:
  accepted: true
  hostname: k3s-node4.lab
  hardware:
    compute:
      processors:
        - manufacturer: Intel
          productName: Intel(R) Celeron(R) CPU N3000 @ 1.04GHz
    system:
      family: Default string
      manufacturer: GIGABYTE
      productName: GB-BACE-3000
      serialNumber: Default string
      skuNumber: Default string
    version: 1.x
  pxeBootAlways: true
  environmentRef:
    namespace: default
    name: amd64
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
    - op: add
      path: /machine/install/extraKernelArgs
      value:
        - console=ttyUSB0,115200
    - op: add
      path: /machine/install/extensions
      value:
        - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
        - image: ghcr.io/siderolabs/i915-ucode:20230310
        - image: ghcr.io/siderolabs/intel-ucode:20230214
