---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  name: d92c1c15-a61d-e53c-f392-a0f566506566
  labels:
    metal.sidero.dev/serverclass: trigkey
    metal.sidero.dev/machine.type: worker
spec:
  accepted: true
  hostname: k3s-node3.lab
  hardware:
    compute:
      processors:
        - manufacturer: Advanced Micro Devices, Inc.
          productName: AMD Ryzen 5 5560U with Radeon Graphics
    system:
      family: Default string
      manufacturer: AZW
      productName: S5
      serialNumber: Default string
      skuNumber: Default string
      version: Default string
  pxeBootAlways: true
  environmentRef:
    namespace: default
    name: amd64
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: bond0
            dhcp: false
            bond:
              deviceSelectors:
                - hardwareAddr: 20:7b:d2:*
                  driver: cdc_ncm
              mode: 802.3ad
            vlans:
              - vlanId: 200
                dhcp: false
              - vlanId: 110
                dhcp: false
          - deviceSelector:
              hardwareAddr: 20:7b:d2:*
              driver: cdc_ncm
            dhcp: false
          - deviceSelector:
              hardwareAddr: b0:41:6f:*
            dhcp: true
          - deviceSelector:
              hardwareAddr: 00:e0:4c:*
            mtu: 9000
            addresses:
              - 192.168.10.6/30
            routes:
              - network: 192.168.10.12/30
                gateway: 192.168.10.5
    - op: add
      path: /machine/kubelet/nodeIP
      value:
        validSubnets:
          - 192.168.4.0/24
    - op: add
      path: /machine/kernel
      value:
        modules:
          - name: cdc_ncm
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
    - op: add
      path: /machine/install/extensions/-
      value:
        image: ghcr.io/siderolabs/usb-modem-drivers:v1.7.4
    - op: add
      path: /machine/install/extensions/-
      value:
        image: ghcr.io/siderolabs/amd-ucode:20240513
    - op: add
      path: /machine/install/extensions/-
      value:
        image: ghcr.io/siderolabs/amdgpu-firmware:20240513
    - op: add
      path: /machine/install/extensions/-
      value:
        image: ghcr.io/siderolabs/realtek-firmware:20240513
