---
apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: amd64
spec:
  initrd:
    url: https://github.com/talos-systems/talos/releases/download/v1.5.4/initramfs-amd64.xz
    sha512: 424080d37e9396c2d0eba820657514b7a26f8cb298555b634443d53dde5156bb5725708fd1247248e89fd3e04e51192f3c7d1e3f0cb353f88aa3ee321789688d
  kernel:
    args:
      - console=tty0
      - console=ttyS0
      - console=ttyUSB0,115200
      - consoleblank=0
      - earlyprintk=ttyS0
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - slab_nomerge=
      - talos.platform=metal
    url: https://github.com/talos-systems/talos/releases/download/v1.5.4/vmlinuz-amd64
    sha512: 220518494e7344b16f360a52e720ebaaa2abc6d16afcd5c8d332b6e5fdec52e90ec8df586d43263c4f487a64ce95fb33f48ead3567bb91c924ec0fba7e7d40f1
