---
apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: amd64
spec:
  initrd:
    url: https://factory.talos.dev/image/2365b720c2de7af6a43c404c390b4397ea1968e5d7c4585bb9df95c58f1bc93d/v1.7.5/initramfs-amd64.xz
  kernel:
    args:
      - console=tty0
      - console=ttyS0
      - console=ttyUSB0,115200
      - consoleblank=0
      - earlyprintk=ttyS0
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - slab_nomerge=
      - talos.platform=metal
      - net.ifnames=0
    url: https://factory.talos.dev/image/2365b720c2de7af6a43c404c390b4397ea1968e5d7c4585bb9df95c58f1bc93d/v1.7.5/kernel-amd64
