---
apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.4/initramfs-arm64.xz
    sha512: 9644feb333d2addd52ed86563a1c54731fe23632074a38b351de236e340de9c132e7869953372d0cdc53bde827c3b04cc2faeb13391cd5d438709443abc73aaf
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.4/vmlinuz-arm64
    sha512: 816562fa87a19a865bc0d60028bf7effc310f6c07df4427d1cd32f8363e3a88e33bc588197b67ef947720e3b27ecc2a39159d6c5f2eb7a21d0f75e8145fb1652
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
      - net.ifnames=0
