---
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.3.3/initramfs-arm64.xz
    sha512: 54cc25dbed195cce9d49317c7ee6305dcc2bdd88dd4f489694b3d52e2fde7259384e9dc7ae0300a1985554537669f8b38dcda028b6dd67a90ecb7b4abe87d132
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.3.3/vmlinuz-arm64
    sha512: 03198709c86345a20b974491272b9070cc75c7a5ae1f3e78eeec77848a71851c0b5b33d66b9de6115a8e9ecacdf79d3ed8f60736457663140fca1b2e92274aa2
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
