---
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.4.5/initramfs-arm64.xz
    sha512: f4a77d2605868ab0ca92dbb5cc749ab6167cdbf0832756cbf184706231e2d3ae391ea85923eaa8d4b87a9409a717265fa2a89cf25802bc46b85b42bb9f1a28b7
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.4.5/vmlinuz-arm64
    sha512: a782b531e8a15ee73aea8573558fe5d01417b4d847fe8122ffef686b468e05174ab62c25df950124b2f50605237bea58658ebd46ae975ea32670e07b182c5edd
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
