---
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: rpi4-beta
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.4.0-beta.0/initramfs-arm64.xz
    sha512: a264c8c1fc82771fe346a1157f12a995edd957d341cee07ca08fb2c3301f5436048905e0364525eed68292bd4a09156c93bdf2d7beba48eeb770987833e0c30f
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.4.0-beta.0/vmlinuz-arm64
    sha512: fe2bf78f403d9196b46d1f8173a5ba3ca206a488d6bc33f622fe68ee6a5d1c05b8c0182c1c8258a5f39aa4ca7215c3cfc443113c765255009b924370d2788a24
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
