---
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.3.5/initramfs-arm64.xz
    sha512: 673480d0edc113e8fccee1f3d09a742532e5ff9f9a8a4b6349c9b486bd51c478c1d6c883a959694b3555cfe43fc0340bb66143b87e5d3c4863e0faebca1f6e7d
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.3.5/vmlinuz-arm64
    sha512: d7afc0763f9820f62ab2915176fed3584faa7eb078a7600835bd7b91d82a88506361c09dfd4351355568014ca01a129a064998a9c2cfd2b9f7b6c1c1ed383bc4
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
