---
apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.6/initramfs-arm64.xz
    sha512: 8cf88051d7639c3b5bcc589b20a59088913c85c1a1227aab8c6f06dbbf4f5d6429cfba385e9d4df3a8f14f27b1d2198d6eec8e5c20141b4ce36c5a9b2ca9c9ab
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.6/vmlinuz-arm64
    sha512: b63100412f65f0471d3a334e7fcca90936452389b148e0514faa36721cfcf4e30674130fd7fa0fd7715147a811fa7a673f18c603ee43051b1eccefebedcb2012
    args:
      - console=tty0
      - console=ttyS0
      - console=ttyUSB0,115200
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
      - net.ifnames=0
