---
apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.2/initramfs-arm64.xz
    sha512: 063dfb142593ebeeae600657e3c38733bd7b78a2e91b4a188c7fa089b24ac0c33fee2860cf26606f2d51b751f08aa87cf309c04eaea9f88ea00bd2ed616243d4
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.2/vmlinuz-arm64
    sha512: 33f3526b48a7ac971b4eec147296f8c08379fd29cc26825c50046965ac4c47d127a5e75212291b5ae5cc6db875852fe0d7994c6a3295d14f2f7dc45a37269739
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
