---
apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://factory.talos.dev/image/f8a903f101ce10f686476024898734bb6b36353cc4d41f348514db9004ec0a9d/v1.7.5/initramfs-arm64.xz
  kernel:
    url: https://factory.talos.dev/image/f8a903f101ce10f686476024898734bb6b36353cc4d41f348514db9004ec0a9d/v1.7.5/kernel-arm64
    args:
      - console=tty0
      - console=ttyS0
      - console=ttyUSB0,115200
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
      - net.ifnames=0
      - ipv6.disable_ipv6=1
