---
apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.3/initramfs-arm64.xz
    sha512: edba9040bd5fac1777b6a48410a3e691b1cdf11c4348a341bd48f13bfce07ef61e23aaefd6cc59350848ae974e1867b2a4a646f8d339aad704e250af50e89d8d
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.3/vmlinuz-arm64
    sha512: 68ba9535a2a2ae901ff3f2354f6bb38a0d4d3622a99f2b4980f213c46fe07102292a75f6db6822e335f106b0e03f334d5c4e68b7f8fc1b9ab81bae91b2190410
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
