---
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.4.8/initramfs-arm64.xz
    sha512: 9a396cdddedd310d78958420e1161742d2e6513745374b1c382a6e0e2e1a4b83631fa284775d274ab3515ee65f9961edf5f071e58f3cc441f12f714f13e47dac
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.4.8/vmlinuz-arm64
    sha512: 2be75e96428ad5086a7733a0764c7c60b0aad8a17fc50bf15561c314c0af3591bdec618f622b52440ec4f6daa3838f196976ed26ba78af4bce932d49b5f96a18
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
