---
fail_fast: false
repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '150']
        exclude: .*\.enc\.yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.0
    hooks:
      - args:
          - --config-file
          - .github/linters/.yamllint.yaml
        id: yamllint
        exclude: .*\.enc\.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=2000]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: remove-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: fix-smartquotes
      - id: fix-ligatures

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks-docker

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 39.264.0
    hooks:
      - id: renovate-config-validator
