apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
    namespace: tw
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:yi18BQ8=,iv:3dgr7OV77faTrnOCSKWYjyBZiEx5tXoAXXuZE5W5bPk=,tag:hxyTkENIbjBsqNTzHbiZGw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:9rlPJ0loXibfJawY7ng2xaCuk08=,iv:hxmR17iUPzuxlwKI0kiQJjeRDMuSEKASPHcCrSU31n0=,tag:f3X+YXk+Iwg5iOSB9hLcbQ==,type:str]
    nextcloud-token: ENC[AES256_GCM,data:zdS8Qx3TqkzUe62pfKI2iBKBzDlmx9mkZQ==,iv:88NpZrTD1bNng6cNeug1W7StnmyUrlSNCkvXbX01boo=,tag:0Oy3ckhSWEtUvwXnsxeMmA==,type:str]
    smtp-username: ENC[AES256_GCM,data:gv6PP1V415fKoYQOUih7C87/nwfweirbeZ4LMSiFcw==,iv:LvzJnNWKtYQp3Yyu/nTLaPVmh92n2HrEB5kW9EWiaUA=,tag:ZVSznj9rWSrQFb+KMwgXIA==,type:str]
    smtp-password: ENC[AES256_GCM,data:5I6bl/tP2uaDGu70B9FgIQ==,iv:zfkEem0GGtfaVPb8uu+r6YMzjXLujC66+bYQGZS72pg=,tag:CgUi/4GrSTF64nMrw952VQ==,type:str]
    smtp-host: ENC[AES256_GCM,data:r6Owrfq4UHEZ+P8neWliN+e4,iv:y29c4FWJkmujlqbjSyExsO8FmowYxgQ1l2DHjGsPI48=,tag:45X0qceegYhNFqozoS4fUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheHpMOGQ3TlI4U0VjdHJ4
            VVpRbDlId3RodmpqdkRlYjA2Ryt5RW1KV3k0Ck9HNnZQUHo1OW1pbE96cjE2aVlz
            WDVRTk5Vdkh5VVpWZGNzMmtPSHVBQ2sKLS0tIE8va3g3dzZpMnk0MUlMbDVwUk9w
            QTdIcFc4VGVac0E3VDRSMFF4OURPSEEKAP6hn5MGblJ+LQjF+JT4SuNm4Q1bajwE
            L9+DR4Jjb30RUjy895dFsLofy6yFEnSnVO3lYbgD51KSog2kdw//Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T09:08:38Z"
    mac: ENC[AES256_GCM,data:N7tvNppKSaEa6vIrI4WeXpaa0c/lhbwz7prIyS9p03Yly+FoaFxS9SZzOvf+81XOP4YerbdjPeeTkzzHPed/rukwivMt08m0FXy1KpzrLUJE4hjUATl6dhRc7f9AVLy9ItVdtf7FiB8RfFs6zIdQmZH3RmXKMr7TyGx8b6pq19w=,iv:aFW/eFNNB1OPLuWegzrgaFm8ZEplxLWhWkLPG0geCRM=,tag:8rwbI74e38/CJYPn0Vi76g==,type:str]
    version: 3.13.2
