---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../controllers/cilium-helm.yaml
  - metallb.yaml
  - descheduler.yaml
  - ../../controllers/traefik.yaml
  - ../../controllers/cert-manager-csi-driver.yaml
  - generic-device-plugin.yaml
  - images.yaml
patches:
  - path: cilium-values.yaml
    target:
      kind: HelmRelease
      name: cilium
  - path: traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
configMapGenerator:
  - name: cilium-values
    namespace: flux-system
    files:
      - ../../controllers/cilium-values.yaml
configurations:
  - kustomizeconfig.yaml
