---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus-cni
  namespace: flux-system
spec:
  interval: 30m
  releaseName: multus-cni
  targetNamespace: kube-system
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: multus-cni
      version: "1.1.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    global:
      storageClass: freenas-iscsi-csi
    image:
      debug: true

