---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: multus-cni
  namespace: flux-system
spec:
  interval: 30m
  releaseName: multus-cni
  targetNamespace: kube-system
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: multus-cni
      version: 2.1.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    global:
      storageClass: freenas-iscsi-csi
    image:
      debug: true
    initContainers:
      - name: clean-multus-conf
        image: busybox:1.28
        command: [rm, -rf, /bitnami/multus-cni/host/etc/cni/net.d/00-multus.conflist]
        resources: {}
        volumeMounts:
          - name: cni-net-dir
            mountPath: /bitnami/multus-cni/host/etc/cni/net.d
        securityContext:
          privileged: true
          runAsUser: 0
          runAsNonRoot: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: whereabouts
  namespace: flux-system
spec:
  interval: 30m
  releaseName: whereabouts
  targetNamespace: kube-system
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: whereabouts
      version: 1.1.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    global:
      storageClass: freenas-iscsi-csi
    image:
      debug: true
