---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  values:
    persistence:
      enabled: false
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: external-pool
        metallb.universe.tf/loadBalancerIPs: 192.168.5.240
      labels: {}
      spec:
        externalTrafficPolicy: Local
      loadBalancerSourceRanges: []
      externalIPs: []
      additionalServices:
        internal:
          type: LoadBalancer
          labels:
            traefik-service-label: internal
          annotations:
            metallb.universe.tf/address-pool: internal-pool
            metallb.universe.tf/loadBalancerIPs: 192.168.4.240
          spec:
            externalTrafficPolicy: Local
          loadBalancerSourceRanges: []
          externalIPs: []
    ports:
      traefik:
        expose:
          default: false
          internal: true
      web:
        expose:
          default: true
          internal: true
      websecure:
        expose:
          default: true
          internal: true
    experimental:
      plugins:
        rewrite-body:
          moduleName: github.com/traefik/plugin-rewritebody
          version: v0.3.1
        cookiePathPrefix:
          moduleName: github.com/SchmitzDan/traefik-plugin-cookie-path-prefix
          version: v0.0.3
