---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baby-agent
  namespace: kerberos
  labels:
    io.kompose.service: kerberos
    io.kerberos.agent: baby
spec:
  selector:
    matchLabels:
      io.kompose.service: kerberos
      io.kerberos.agent: baby
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: kerberos
        io.kerberos.agent: baby
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
        - name: perms-config
          volumeMounts:
            - name: kerberos-data
              mountPath: /home/agent/data/config
              subPath: config
            - name: kerberos-data
              mountPath: /home/agent/data/recordings
              subPath: recordings
            - name: kerberos-data
              mountPath: /home/agent/data/snapshots
              subPath: snapshots
            - name: kerberos-data
              mountPath: /home/agent/data/cloud
              subPath: cloud
          image: busybox:1.28
          command: ['sh', '-c', 'chown -R 100:101 /home/agent/data']
        - name: download-config
          image: kerberos/agent:1b96d01
          volumeMounts:
            - name: kerberos-data
              mountPath: /home/agent/data/config
              subPath: config
          command:
            [
              "cp",
              "/home/agent/data/config.template.json",
              "/home/agent/data/config/config.json",
            ]
      containers:
        - name: baby-agent
          image: kerberos/agent:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: CAM_IP
              value: 192.168.2.30
            - name: CAM_PASSWD
              valueFrom:
                secretKeyRef:
                  name: kerberos
                  key: CAM_PASSWD
            - name: AGENT_TIMEZONE
              value: Europe/Madrid
            - name: AGENT_NAME
              value: baby-agent
            - name: AGENT_CAPTURE_IPCAMERA_RTSP
              value: rtsp://admin:$(CAM_PASSWD)@$(CAM_IP):554/h264_hd.sdp
            - name: AGENT_CAPTURE_IPCAMERA_ONVIF_XADDR
              value: $(CAM_IP):2020
            - name: AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME
              value: admin
            - name: AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD
              value: $(CAM_PASSWD)
          volumeMounts:
            - name: kerberos-data
              mountPath: /home/agent/data/config
              subPath: config
            - name: kerberos-data
              mountPath: /home/agent/data/recordings
              subPath: recordings
            - name: kerberos-data
              mountPath: /home/agent/data/snapshots
              subPath: snapshots
            - name: kerberos-data
              mountPath: /home/agent/data/cloud
              subPath: cloud
      volumes:
        - name: kerberos-data
          persistentVolumeClaim:
            claimName: baby-agent-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-agent
  namespace: kerberos
  labels:
    io.kompose.service: kerberos
    io.kerberos.agent: main
spec:
  selector:
    matchLabels:
      io.kompose.service: kerberos
      io.kerberos.agent: main
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: kerberos
        io.kerberos.agent: main
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
        - name: perms-config
          volumeMounts:
            - name: kerberos-data
              mountPath: /home/agent/data/config
              subPath: config
            - name: kerberos-data
              mountPath: /home/agent/data/recordings
              subPath: recordings
            - name: kerberos-data
              mountPath: /home/agent/data/snapshots
              subPath: snapshots
            - name: kerberos-data
              mountPath: /home/agent/data/cloud
              subPath: cloud
          image: busybox:1.28
          command: ['sh', '-c', 'chown -R 100:101 /home/agent/data']
        - name: download-config
          image: kerberos/agent:1b96d01
          volumeMounts:
            - name: kerberos-data
              mountPath: /home/agent/data/config
              subPath: config
          command:
            [
              "cp",
              "/home/agent/data/config.template.json",
              "/home/agent/data/config/config.json",
            ]
      containers:
        - name: main-agent
          image: kerberos/agent:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: CAM_IP
              value: 192.168.2.31
            - name: CAM_PASSWD
              valueFrom:
                secretKeyRef:
                  name: kerberos
                  key: CAM_PASSWD
            - name: AGENT_TIMEZONE
              value: Europe/Madrid
            - name: AGENT_NAME
              value: main-agent
            - name: AGENT_CAPTURE_IPCAMERA_RTSP
              value: rtsp://admin:$(CAM_PASSWD)@$(CAM_IP):554/h264_hd.sdp
            - name: AGENT_CAPTURE_IPCAMERA_ONVIF_XADDR
              value: $(CAM_IP):2020
            - name: AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME
              value: admin
            - name: AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD
              value: $(CAM_PASSWD)
          volumeMounts:
            - name: kerberos-data
              mountPath: /home/agent/data/config
              subPath: config
            - name: kerberos-data
              mountPath: /home/agent/data/recordings
              subPath: recordings
            - name: kerberos-data
              mountPath: /home/agent/data/snapshots
              subPath: snapshots
            - name: kerberos-data
              mountPath: /home/agent/data/cloud
              subPath: cloud
      volumes:
        - name: kerberos-data
          persistentVolumeClaim:
            claimName: main-agent-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kerberos
  name: main-agent
  namespace: kerberos
spec:
  ports:
    - name: main
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    io.kompose.service: kerberos
    io.kerberos.agent: main
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kerberos
  name: baby-agent
  namespace: kerberos
spec:
  ports:
    - name: baby
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    io.kompose.service: kerberos
    io.kerberos.agent: baby
