---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baby-agent-data
  namespace: kerberos
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main-agent-data
  namespace: kerberos
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
