---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sipwork.pro
  namespace: traefik
spec:
  secretName: sipwork.pro-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - "sipwork.pro"
    - "*.sipwork.pro"
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: app=kubed
