---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sipwork.pro
  namespace: traefik
spec:
  secretName: sipwork.pro-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - sipwork.pro
    - '*.sipwork.pro'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: infra,sipwork
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: infra,sipwork
