---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: home-assistant
  namespace: sipwork
spec:
  image: lscr.io/linuxserver/homeassistant
  interval: 12h
  exclusionList:
    - ^develop.*
    - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: home-assistant
  namespace: sipwork
spec:
  imageRepositoryRef:
    name: home-assistant
    namespace: sipwork
  policy:
    semver:
      range: '>=2023.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: mosquitto
  namespace: sipwork
spec:
  image: eclipse-mosquitto
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mosquitto
  namespace: sipwork
spec:
  imageRepositoryRef:
    name: mosquitto
    namespace: sipwork
  policy:
    semver:
      range: '>=2.0.18'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: zigbee2mqtt
  namespace: sipwork
spec:
  image: koenkk/zigbee2mqtt
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: zigbee2mqtt
  namespace: sipwork
spec:
  imageRepositoryRef:
    name: zigbee2mqtt
    namespace: sipwork
  policy:
    semver:
      range: '>=1.34.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: node-red
  namespace: sipwork
spec:
  image: nodered/node-red
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-red
  namespace: sipwork
spec:
  imageRepositoryRef:
    name: node-red
    namespace: sipwork
  filterTags:
    pattern: .*-debian
  policy:
    semver:
      range: '>=3.1.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: sipwork
  namespace: sipwork
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        pk8s: [sipwork] Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
    push:
      branch: flux-image-updates-sipwork
  update:
    path: ./apps/pk8s/sipwork
    strategy: Setters
