###
kimaiAppSecret:
kimaiAdminPassword:
kimaiAdminEmail:
kimaiMailerFrom:
###
image:
  tag: apache-2.2.0-prod # {"$imagepolicy": "sipwork:kimai2:tag"}
existingSecret: kimai
updateStrategy:
  type: Recreate
  rollingUpdate:
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: kimai.sipwork.pro
  annotations:
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd,traefik-internal-ipwhitelist@kubernetescrd
  extraTls:
    - secretName: sipwork.pro-tls
persistence:
  enabled: true
  size: 5Gi
  selector:
    matchLabels:
      org.democratic-csi.manual: sipwork-kimai
mariadb:
  enabled: true
  auth:
    existingSecret: kimai-db
  primary:
    persistence:
      enabled: true
      selector:
        matchLabels:
          org.democratic-csi.manual: sipwork-kimai-db
