---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: phpmyadmin
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: sipwork
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: phpmyadmin
      version: 16.0.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: php.sipwork.pro
      annotations:
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd,traefik-internal-ipallowlist@kubernetescrd
      extraTls:
        - hosts:
            - php.sipwork.pro
          secretName: sipwork.pro-tls
    db:
      allowArbitraryServer: true
