---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: semaphore
  namespace: flux-system
spec:
  interval: 12h
  url: https://semaphoreui.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphoreui
  namespace: flux-system
spec:
  interval: 30m
  releaseName: semaphoreui
  targetNamespace: sipwork
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: semaphore
      version: 16.0.x
      sourceRef:
        kind: HelmRepository
        name: semaphore
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: semaphoreui-values
      valuesKey: values-semaphoreui.yaml
    - kind: Secret
      name: semaphoreui-config
      valuesKey: values-secret-semaphoreui.yaml
