---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sipwork-wp
  labels:
    app: sipwork-wp
spec:
  capacity:
    storage: 10Gi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-5dad0e7a-8a41-4187-b0c7-558a7760b0d5
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-5dad0e7a-8a41-4187-b0c7-558a7760b0d5-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sipwork-db
  labels:
    app: sipwork-db
spec:
  capacity:
    storage: 8Gi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-02794d76-a6e4-42b5-9cd5-7c8074c6a3b3
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-02794d76-a6e4-42b5-9cd5-7c8074c6a3b3-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sipwork-kimai
  labels:
    org.democratic-csi.manual: sipwork-kimai
spec:
  capacity:
    storage: 5Gi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-1791b423-e062-4f1e-ba33-229c02a58ddb
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-1791b423-e062-4f1e-ba33-229c02a58ddb-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sipwork-kimai-db
  labels:
    org.democratic-csi.manual: sipwork-kimai-db
spec:
  capacity:
    storage: 4Gi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-50012aed-248e-437a-8952-2147ba7a8bd0
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-50012aed-248e-437a-8952-2147ba7a8bd0-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
