---
wordpressUsername: ENC[AES256_GCM,data:usYTwWTi4h8bQgNm05207xjH,iv:KJTo0KDZu1eZADhcE3/Vr83SvogCpvJRmWr9+Zwe/eM=,tag:P42m2VHsRLR3eiOSbutuYw==,type:str]
wordpressPassword: ENC[AES256_GCM,data:WfzGDLtN6Bn79qXdqyaGDQ==,iv:Oz9qODZWPvqm++kmZocCRCmpWi0o5ODMzLVOw+dPr7w=,tag:RChyncwT6QNIWw0wFRUn9A==,type:str]
wordpressEmail: ENC[AES256_GCM,data:ihLNvzluyEbduRfC+/EgkC8=,iv:Jk+5ryn1vg5nI8vknPQdXtE7FaDr6VjV5SjQh6JZOUc=,tag:w86/0xLJqdKyIDRKzBSm2g==,type:str]
wordpressFirstName: ENC[AES256_GCM,data:ZZ4RFjBj,iv:tbeK8oqwkFC2Ey8J0YGzxywx3AGn9cMSmESSrqwzVmE=,tag:1ba/djWMVhI/hx/mIlKPgw==,type:str]
wordpressLastName: ENC[AES256_GCM,data:/ecASg==,iv:ZxqNUWT/SCW5VwxQc4HGgUVhPhjObejkHNOCputNhW0=,tag:dWIs0o7bn76Fn1aGkqpv9g==,type:str]
wordpressBlogName: ENC[AES256_GCM,data:NrbtiHGyTD897CM=,iv:XVetYEMAqqB3TcHp1PebyQnTZ0/yYVd4JPVRSBfbOUo=,tag:Vdrpbz54jL49X8rIVHbK0Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU2MvamVYTVh3TzNQcEQz
        R3VOaUZsQUxOeG5USEszMkRjb0VRaWd1VzM4CmNHV3orMG90ZmRDQXA1dWhjeUN5
        cjdvSmpOWU12YTM3OThuelJDVGRQT3MKLS0tIFpELzgybGFrVVUxOStMOWpZM1gw
        VjBCODd6bmxVcUg2L01rYzUrZDRROG8KQtcRwdGFrzzLumgiwz2p8lXBBD3LCHk9
        vlYokCsNF6/XDVXltQnuCPny4seuMaiS4OgjuSxxSuw0/M8r2n++gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-10-18T13:33:14Z'
  mac: ENC[AES256_GCM,data:eOi8aPE7chDG80NtPKm7d+4tgFQ525i/2ZinY/U8rW4DLn09ngqoi1fWHZjXxXL+hWK6OEyctWFs2qGbRwj1zoKEkVvuFsuaEydR/lPVdCJFGOKnJJzlrEyPuPcpy2E+azv9x36NmvDGnoky7m8uo/hPTHJ/MKG+/5iqACpJ/Zo=,iv:SPaAkxxFrNS2xA2AK545h7E4jW3d4SU+XnJzDI3w09o=,tag:1yG2Sz/cCfVGuLcP/lfNHg==,type:str]
  pgp: []
  encrypted_regex: .*
  version: 3.7.3
