---
# secret-values
wordpressUsername:
wordpressPassword:
wordpressEmail:
wordpressFirstName:
wordpressLastName:
wordpressBlogName:
#
existingSecret: wp-wordpress
#
replicaCount: 1
updateStrategy:
  type: Recreate
  rollingUpdate:
wordpressScheme: https
service:
  type: ClusterIP
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: sipwork.pro
  extraHosts:
    - name: www.sipwork.pro
      path: /
    - name: ww2.sipwork.pro
      path: /
  annotations:
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd,traefik-internal-ipwhitelist@kubernetescrd
  extraTls:
    - hosts:
        - sipwork.pro
        - www.sipwork.pro
        - ww2.sipwork.pro
      secretName: sipwork.pro-tls
persistence:
  enabled: true
  selector:
    matchLabels:
      app: sipwork-wp
mariadb:
  enabled: true
  auth:
    existingSecret: wp-mariadb
  primary:
    persistence:
      enabled: true
      selector:
        matchLabels:
          app: sipwork-db
metrics:
  enabled: true
multisite:
  enable: true
  host: sipwork.pro
