---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-snapshot
  namespace: flux-system
spec:
  interval: 10m
  releaseName: snapshot-controller
  targetNamespace: democratic-csi
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: snapshot-controller
      version: 0.2.4
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    controller:
      enabled: true
      rbac:
        enabled: true
      replicaCount: 1
