---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  interval: 30m
  releaseName: velero
  targetNamespace: velero
  serviceAccountName: helm-controller
  chartRef:
    kind: HelmChart
    name: velero
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: velero-values
      valuesKey: values-velero.yaml
    - kind: Secret
      name: velero-config
