credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:MNUtJkM2MLJSA2OURdhGpxpAqlmz0E0z8Ewyyxg9RnuALRk/uM7fsKygUjTXw6finIHnGxhNLDbAEqhAW1GQVU6DjMEyy7TjR+deRQmpyZhICXh6chYTj7KowtHHCYzpOlbYjrlhZKDQ2fhjZv+vmA==,iv:7cvZSNvtSlWzDkDTLMHHanTARCjuyt3POh1OygVrbe4=,tag:66wYtVxayfs1+qZYDflTdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cFFqejFDZDduMHNQZ3ov
            ZmVhNzYrbHlqb25ybmZrVE1KR0J4Ti9DZFF3ClVNeGdmd0RZcjBBTzdTeG55c01Q
            VXlmNjNpTmx6dWxVMk5VZTlkTU51Sm8KLS0tIHpTSDNscTI1NlBIejFtNzNCY0Rz
            VWFsZmkxenl0RktHSG52cHNQVmJvdVEKRJwOLSOKUHaaOOOuMP7Vf+LmVg9JlymA
            3PsDhpv030Lmm0OQGJJC8tE8P0vKAZS6kUnDnLbI+sGYEuDWXkaraQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T00:04:33Z"
    mac: ENC[AES256_GCM,data:oJzjQ+V1VZayzqEefOmFPIOmuR+v5/WpMT+QOXtsQB3jSwO9cixqxQBG29o9OcrzUJ30gMKC8heUMUI/FrMo2SgOeMeE68V6t/kNrjrGG0ZqlZUOOGMLSwN4Y60iX+L1FBGu4D7lIiMe7N5D450g+E45tqEFlYJlCftBq8UGBxc=,iv:MHEceXCtrXBoQ5YIbPQ6flY1VcX0B6sfTkSOmu81tWo=,tag:yA2JZp5W3qCI9PzHTlTr/Q==,type:str]
    pgp: []
    encrypted_regex: .*
    version: 3.7.3
