---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: coder-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.coder.com/v2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: flux-system
spec:
  interval: 30m
  releaseName: coder
  targetNamespace: coder
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: coder
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: coder-charts
        namespace: flux-system
      interval: 12h
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-secrets
              key: url
        - name: CODER_ACCESS_URL
          value: https://coder.torreviejawireless.org
        - name: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
          value: torreviejawireless
        - name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
          value: "true"
        - name: CODER_OAUTH2_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-secrets
              key: github_oauth2_client_id
        - name: CODER_OAUTH2_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-secrets
              key: github_oauth2_client_secret
        - name: CODER_GITAUTH_0_ID
          value: "primary-github"
        - name: CODER_GITAUTH_0_TYPE
          value: github
        - name: CODER_GITAUTH_0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-secrets
              key: github_auth_client_id
        - name: CODER_GITAUTH_0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-secrets
              key: github_auth_client_secret
      service:
        type: ClusterIP
      ingress:
        enable: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd
        host: coder.torreviejawireless.org
        tls:
          enable: true
          secretName: tw-tls
