apiVersion: ENC[AES256_GCM,data:r8Q=,iv:xquMgMoxPSfT3s+9jHU/pVay/b0/vr0joIOrHVP6Le4=,tag:T5KEb5R1ggAfKxNvCzM7UA==,type:str]
kind: ENC[AES256_GCM,data:sEiJQ8x8,iv:Zv8Tdyg0VHWz/vUc+b+vLJkwbbZR8mPSpM8xY6u56+Y=,tag:58mdEbmm9chRUEeTXB/C6A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ySAmwk7nqjyTfYUUMA==,iv:TpV5QIrAWTCRCeg+DJszcJ8zzZUqHGFem2jzh6ssNBs=,tag:H7HFm37UhUCsnCpo9uwwzA==,type:str]
    namespace: ENC[AES256_GCM,data:mTkQS60=,iv:OS7x7yWqfgRwy05y1EY11pYiyA/RxtPimfEhXlzOVRY=,tag:X9KJSJwPfxZzWG+GO+0gdQ==,type:str]
type: ENC[AES256_GCM,data:aQWadyd6,iv:Kxrbk0en5JR39qayX5IztImLkeWkMMOHz65fRse7Rjk=,tag:sxZtvOFdpLaB2vUUYPIZgQ==,type:str]
stringData:
    url: ENC[AES256_GCM,data:icQvwdLaDtZclLn0qIpXQExN2bVBITYoHa8VXNecqvWbPFJ7JkY1BAotIjoWGxG3GU+w5NpU7ZzdnY2mM0D5V3tSW1ABrvwzA9O0o6cs3NQqYCrz6uv/j8DXHnE/LtNUivlxY5wBOyA=,iv:xgKy0I6xyp5f4x4DZeT65CFVYJBfjMsuVbAZEyr66GI=,tag:hI9zqmpz7+srrJwyuXQBig==,type:str]
    github_oauth2_client_id: ENC[AES256_GCM,data:6i1b/WgYNCKUQP5k5c31mzgAdZA=,iv:WSvUDfHWTCH8LXJ+lfZBQdr3MgFlmfrpuGztHT2lhgI=,tag:SFvb00hjkaYQAHipmfylmw==,type:str]
    github_oauth2_client_secret: ENC[AES256_GCM,data:TxuQWz6J7N5VlWTosP8468hTlpSGaCPAe2VVE0pg5srXy8xrWr5xUA==,iv:gS5MQJMpdIueZqRIOw+cFYl99TOptGArt1DSy6DtAHk=,tag:ecNmToawp2BntSCzNO+eLw==,type:str]
    github_auth_client_id: ENC[AES256_GCM,data:xxvUtXAzRxcERSTdSh66Ke43sBg=,iv:VhvjMkNVkxhEQE6afgR+nL8CL1rWj9zDFnQTuME6ZnY=,tag:jNqq8cl3o3wa4jY1DMFHxw==,type:str]
    github_auth_client_secret: ENC[AES256_GCM,data:Xd9DwxIPlvwuOk8nxpKX9Uu4Ly3wZUxo3aXh7ohe3XRygkhcDaZVhw==,iv:C6UsLp49U3LJAHcPfC9VTpYT0656qYOMF4BnwpgYhIM=,tag:ecU09puYMU54gBuBfF2GYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT1Q3bVZ2UjdQQTRMMW9I
            bkxRZTAzTjFmSWh6aGhYSWlOZ2w0YU43b2djCitUNWNSNmlrRWQwWmFzaWtpOTlh
            TDFTZE9RczdNUmVTaVh4SlN0alFsVk0KLS0tIGxUaXg5MkhmbngwZU5KTzhuNEpn
            REhnR3FydXNtdTFhNFg4aWNMQ3FnOXcK1a9B+LQ8WF/UomGcMAZcbwQcxpYR7DbV
            /6VSbxBCJEMMeEoo7yvN4YhCoyA1EJcfdmdlnrlHfCummEnjicC+NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-16T11:03:21Z"
    mac: ENC[AES256_GCM,data:wHlRswWGDNbzVnhTziznXlO0oJknq/YwbZ01aXwPX/iDX2S/F818UV/QSoH+ZNHuJe1h3oVrT6rCIaM0JaghLtPKRy6kUYgwbZbxHt9/P1p7Gms3QipkCveae0fOO86EZj9RuXpUc3Ck17FQkAtJmZR1yr1jvQSwSJBxn57M1os=,iv:EZkp/unkSDusuPsyrGhI3ZP/VnWaoqUdOhLprlrV1Bs=,tag:AcoYzGk4MnEVW0eTICtInw==,type:str]
    pgp: []
    encrypted_regex: .*
    version: 3.7.3
