---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 5m
  chart:
    spec:
      version: 3.12.x
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 60m
  # https://artifacthub.io/packages/helm/metrics-server/metrics-server
  values:
    metrics:
      enabled: false
    serviceMonitor:
      enabled: true
