---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: comunicacioncientifica.info
  namespace: traefik
spec:
  secretName: comunicacioncientifica.info-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - "comunicacioncientifica.info"
    - "*.comunicacioncientifica.info"
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: app=kubed
