---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: comunicacioncientifica.info
  namespace: traefik
spec:
  secretName: comunicacioncientifica.info-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - comunicacioncientifica.info
    - '*.comunicacioncientifica.info'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: umh
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: umh
