---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/sops: enabled
resources:
  - certificate.yaml
  - traefik.yaml
  - wordpress.yaml
secretGenerator:
  - name: wp-config
    namespace: flux-system
    files:
      - values.yaml=wp-secret-values.enc.yaml
configMapGenerator:
  - name: wp-values
    namespace: flux-system
    files:
      - values-wp.yaml=wp-values.yaml
configurations:
  - kustomizeconfig.yaml
