---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: flux-system
spec:
  interval: 30m
  releaseName: wp
  targetNamespace: umh
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: wordpress
      version: 17.1.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: wp-values
      valuesKey: values-wp.yaml
    - kind: Secret
      name: wp-config
