---
# secret-values
wordpressUsername:
wordpressPassword:
wordpressEmail:
wordpressFirstName:
wordpressLastName:
wordpressBlogName:
#
existingSecret: wp-wordpress
smtpExistingSecret: wp-wordpress
#
global:
  security:
    allowInsecureImages: true
image:
  tag: 6.7.2-debian-12-r8
  repository: bitnamilegacy/wordpress
replicaCount: 1
updateStrategy:
  type: Recreate
  rollingUpdate:
wordpressScheme: https
service:
  type: ClusterIP
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: comunicacioncientifica.info
  extraHosts:
    - name: www.comunicacioncientifica.info
      path: /
  annotations:
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd
  extraTls:
    - hosts:
        - comunicacioncientifica.info
        - www.comunicacioncientifica.info
      secretName: comunicacioncientifica.info-tls
persistence:
  enabled: true
  selector:
    matchLabels:
      app: umh-wp
mariadb:
  enabled: true
  image:
    tag: 11.4.5-debian-12-r4
    repository: bitnamilegacy/mariadb
  auth:
    existingSecret: wp-mariadb
  primary:
    persistence:
      enabled: true
      selector:
        matchLabels:
          app: umh-db
metrics:
  enabled: true
