---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-manual
  namespace: flux-system
spec:
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: warn
  interval: 10m
  releaseName: democratic-csi-manual
  targetNamespace: democratic-csi
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.x
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: zfs-manual-values
      valuesKey: values-manual-csi.yaml
