---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
  - ../../controllers/weave-gitops.yaml
  - ../../controllers/traefik.yaml
patches:
  - path: traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
  - path: weave-gitops-values.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
