---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.4.230-192.168.4.239
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: sidero-internal
  namespace: metallb-system
spec:
  ipAddressPools:
    - internal-pool
