---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  values:
    persistence:
      enabled: false
      storageClass: freenas-iscsi-csi
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.io/address-pool: internal-pool
        metallb.io/loadBalancerIPs: 192.168.4.239
      spec:
        externalTrafficPolicy: Local
