---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver
  namespace: flux-system
spec:
  interval: 30m
  releaseName: cert-manager-csi-driver
  targetNamespace: cert-manager
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: cert-manager-csi-driver
      version: 0.5.x
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
  values:
