---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: appscode
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.appscode.com/stable/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
  namespace: flux-system
spec:
  interval: 30m
  releaseName: kubed
  targetNamespace: kube-system
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: kubed
      version: 0.13.x
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
      interval: 12h
  values:
    enableAnalytics: false
