---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/emberstack/helm-charts/reflector
  ref:
    semver: '>=9.1.0'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 12h
  releaseName: reflector
  targetNamespace: kube-system
  serviceAccountName: helm-controller
  chartRef:
    kind: OCIRepository
    name: reflector
