---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - source.yaml
  - release.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values-cilium.yaml=../cilium-values.yaml
configurations:
  - kustomizeconfig.yaml
