---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 30m
  releaseName: cilium
  targetNamespace: kube-system
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: cilium
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
    valuesFrom:
      - kind: ConfigMap
        name: cilium-values
        valuesKey: values-cilium.yaml
