---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: monitoring-controllers
    namespace: flux-system
spec:
    interval: 1h
    retryInterval: 2m
    timeout: 10m
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./monitoring/controllers
    patches:
        - patch: |-
              apiVersion: helm.toolkit.fluxcd.io/v2beta1
              kind: HelmRelease
              metadata:
                name: kube-prometheus-stack
                namespace: monitoring
              spec:
                values:
                  grafana:
                    defaultDashboardsEnabled: true
                    ingress:
                      enabled: true
                      ingressClassName: traefik
                      annotations:
                        traefik.ingress.kubernetes.io/router.tls: "true"
                        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
                        traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd,traefik-internal-ipwhitelist@kubernetescrd
                      hosts:
                        - monitor.torreviejawireless.org
                      tls:
                        - secretName: tw-tls
                          hosts:
                            - monitor.torreviejawireless.org
                      labels: {}
                      path: /
          target:
              kind: HelmRelease
              name: kube-prometheus-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: monitoring-configs
    namespace: flux-system
spec:
    dependsOn:
        - name: monitoring-controllers
    interval: 1h
    retryInterval: 2m
    timeout: 5m
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./monitoring/configs
