---
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    app: kubed
---
apiVersion: v1
kind: Namespace
metadata:
  name: tw
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    app: kubed
---
apiVersion: v1
kind: Namespace
metadata:
  name: plex
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    app: kubed
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: v1
kind: Namespace
metadata:
  name: umh
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    app: kubed
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: v1
kind: Namespace
metadata:
  name: sipwork
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    app: kubed
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    toolkit.fluxcd.io/tenant: sre-team
