---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: unifi
  namespace: metallb-system
spec:
  myASN: 64500
  peerASN: 64512
  peerAddress: 192.168.2.1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.4.240-192.168.4.250
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.2.240-192.168.2.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pk8s
  namespace: metallb-system
spec:
  ipAddressPools:
    - lab-pool
    - lan-pool
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: pk8s
  namespace: metallb-system
spec:
  ipAddressPools:
    - lab-pool
    - lan-pool
