apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: umh
  namespace: velero
spec:
  schedule: '@every 24h'
  template:
    csiSnapshotTimeout: 15s
    includedNamespaces:
      - umh
    itemOperationTimeout: 5s
    ttl: 360h00m00s
    snapshotVolumes: true
  useOwnerReferencesInBackup: false
