---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: pk8s-workers
  namespace: sidero-system
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.5
