---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: pk8s-workers
  namespace: sidero-system
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.3.4
      configPatches:
        - op: add
          path: /machine/install/extensions
          value:
            - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
        - op: add
          path: /machine/kubelet
          value:
            extraArgs:
              rotate-server-certificates: true
        - op: add
          path: /machine/network
          value:
            interfaces:
              - interface: eth0
                dhcp: true
                vlans:
                  - vlanId: 200
                    dhcp: false
