---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: pk8s-cp
  namespace: sidero-system
spec:
  controlPlaneConfig:
    controlplane:
      configPatches:
        - op: add
          path: /machine/kubelet
          value:
            extraArgs:
              rotate-server-certificates: true
        - op: add
          path: /cluster/allowSchedulingOnMasters
          value: false
        - op: add
          path: /cluster/apiServer/admissionControl/0/configuration/exemptions/namespaces/-
          value: democratic-csi
        - op: add
          path: /cluster/apiServer/admissionControl/0/configuration/exemptions/namespaces/-
          value: monitoring
        - op: add
          path: /cluster/extraManifests/-
          value: https://raw.githubusercontent.com/linuxmaniac/home-ops/main/infrastructure/controllers/kubelet-serving-cert-approver.yaml
      generateType: controlplane
      talosVersion: v1.5
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalMachineTemplate
    name: pk8s-cp
  replicas: 3
  version: v1.29.1
