---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: kube-prometheus-stack
          namespace: monitoring
        spec:
          values:
            grafana:
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.tls: "true"
                  traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
                  traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd,traefik-internal-ipwhitelist@kubernetescrd
                hosts:
                  - monitor.torreviejawireless.org
                tls:
                  - secretName: tw-tls
                    hosts:
                      - monitor.torreviejawireless.org
                labels: {}
                path: /
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
