---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./monitoring/controllers
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta2
        kind: HelmRelease
        metadata:
          name: kube-prometheus-stack
          namespace: monitoring
        spec:
          values:
            kubeEtcd:
              endpoints:
                - 192.168.4.4
              service:
                port: 2381
                targetPort: 2381
            kubeScheduler:
              endpoints:
                - 192.168.4.4
              service:
                selector:
                  k8s-app: kube-scheduler
              serviceMonitor:
                selector:
                  matchLabels:
                    k8s-app: kube-scheduler
            kubeControllerManager:
              endpoints:
                - 192.168.4.4
              service:
                selector:
                  k8s-app: kube-controller-manager
              serviceMonitor:
                selector:
                  matchLabels:
                    k8s-app: kube-controller-manager
            grafana:
              defaultDashboardsEnabled: true
              ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                  traefik.ingress.kubernetes.io/router.tls: "true"
                  traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
                  traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd,traefik-internal-ipallowlist@kubernetescrd
                hosts:
                  - monitor.sidero.torreviejawireless.org
                tls:
                  - secretName: sidero.torreviejawireless.org-tls
                    hosts:
                      - monitor.sidero.torreviejawireless.org
                labels: {}
                path: /
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta2
        kind: HelmRelease
        metadata:
          name: loki
          namespace: monitoring
        spec:
          values:
            singleBinary:
              persistence:
                enabled: true
                storageClass: freenas-iscsi-csi
      target:
        kind: HelmRelease
        name: loki
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./monitoring/configs
