apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sidero-secrets
  namespace: flux-system
spec:
  interval: 9m26s
  retryInterval: 10s
  timeout: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./secrets/sidero
  prune: true
  wait: true
