---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: netbootxyz
  namespace: infra
spec:
  image: lscr.io/linuxserver/netbootxyz
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
    - '.*tftp.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: netbootxyz
  namespace: infra
spec:
  imageRepositoryRef:
    name: netbootxyz
    namespace: infra
  policy:
    semver:
      range: '>=0.6.0, <=1.x'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: openssh-server
  namespace: infra
spec:
  image: lscr.io/linuxserver/openssh-server
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: openssh-server
  namespace: infra
spec:
  imageRepositoryRef:
    name: openssh-server
    namespace: infra
  policy:
    semver:
      range: '>=9'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: infra
  namespace: infra
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
          Automated image update

          Automation name: {{ .AutomationObject }}

          Files:
          {{ range $filename, $_ := .Updated.Files -}}
          - {{ $filename }}
          {{ end -}}

          Objects:
          {{ range $resource, $_ := .Updated.Objects -}}
          - {{ $resource.Kind }} {{ $resource.Name }}
          {{ end -}}

          Images:
          {{ range .Updated.Images -}}
          - {{.}}
          {{ end -}}
    push:
      branch: flux-image-updates
  update:
    path: ./apps/pk8s/infra
    strategy: Setters
