---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: gigabyte
spec:
  environmentRef:
    namespace: default
    name: amd64
  qualifiers:
    cpu:
      - manufacturer: Intel
        version: Intel(R) Celeron(R) CPU N3000 @ 1.04GHz
    systemInformation:
      - manufacturer: GIGABYTE
        productName: GB-BACE-3000
        version: 1.x
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
