---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: gigabyte
spec:
  environmentRef:
    namespace: default
    name: amd64
  qualifiers:
    hardware:
      - system:
          manufacturer: GIGABYTE
          productName: GB-BACE-3000
          version: 1.x
      - compute:
          processors:
            - manufacturer: Intel
              productName: Intel(R) Celeron(R) CPU N3000 @ 1.04GHz
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
    - op: add
      path: /machine/install/extensions
      value:
        - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
        - image: ghcr.io/siderolabs/i915-ucode:20230310
        - image: ghcr.io/siderolabs/intel-ucode:20230214
