---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: pk8s-sc-worker
spec:
  selector:
    matchLabels:
      metal.sidero.dev/machine.type: worker
    matchExpressions:
      - key: metal.sidero.dev/serverclass
        operator: In
        values:
          - trigkey
  configPatches:
    - op: add
      path: /machine/kubelet
      value:
        extraArgs:
          rotate-server-certificates: true
    - op: add
      path: /machine/nodeLabels
      value:
        node-role.kubernetes.io/worker: yes
