---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: pk8s-sc
spec:
  selector:
    matchLabels:
      metal.sidero.dev/machine.type: controlplane
    matchExpressions:
      - key: metal.sidero.dev/serverclass
        operator: In
        values:
          - rpi.8gb
  configPatches:
    - op: add
      path: /machine/install/extraKernelArgs/-
      value:
        - console=ttyUSB0,115200
        - net.ifnames=0
