---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: pk8s-sc-worker
spec:
  selector:
    matchLabels:
      metal.sidero.dev/machine.type: worker
    matchExpressions:
      - key: metal.sidero.dev/serverclass
        operator: In
        values:
          - trigkey
  configPatches:
    - op: add
      path: /machine/kubelet
      value:
        extraArgs:
          rotate-server-certificates: true
    - op: replace
      path: /machine/install/extensions
      value:
        - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
    - op: add
      path: /machine/install/extensions/-
      value:
        image: ghcr.io/siderolabs/util-linux-tools:2.40.4
