---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: rpi.8gb
spec:
  environmentRef:
    namespace: default
    name: rpi4
  qualifiers:
    hardware:
      - system:
          manufacturer: Raspberry Pi Foundation
          productName: Raspberry Pi 4 Model B
          version: D03114
  bootFromDiskMethod: ipxe-sanboot
