---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: trigkey
spec:
  environmentRef:
    namespace: default
    name: amd64
  qualifiers:
    hardware:
      - system:
          manufacturer: AZW
          productName: S5
          version: Default string
      - compute:
          processors:
            - manufacturer: Advanced Micro Devices, Inc.
              productName: AMD Ryzen 5 5560U with Radeon Graphics
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
    - op: add
      path: /machine/install/extensions/-
      value:
        - image: ghcr.io/siderolabs/amd-ucode:20230919
        - image: ghcr.io/siderolabs/amdgpu-firmware:20230919
