---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-runners
  namespace: flux-system
spec:
  interval: 30m
  releaseName: arc-sipwork-pro
  targetNamespace: arc-runners
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.x
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
      interval: 12h
  values:
    githubConfigUrl: https://github.com/torreviejawireless
    githubConfigSecret: arc-gh-tw
    maxRunners: 5
    minRunners: 0
    template:
      spec:
        containers:
          - name: runner
            image: mobilecoin/gha-runner:latest
            command: [/home/runner/run.sh]
