apiVersion: v1
kind: Secret
metadata:
    name: code-server
    namespace: tw
type: Opaque
stringData:
    PASSWORD: ENC[AES256_GCM,data:J5r9h5sWav5PFD+H4lQX5A==,iv:zjuxeCZSXLw/47LSXcDtoIH8S39bjeduBC27nlS1XLE=,tag:iRrhBbSWgH2AOmhbtLLLDQ==,type:str]
    SUDO_PASSWORD: ENC[AES256_GCM,data:wHjxxo0X1ZjkqkKWXd4ojw==,iv:8ugYlXuDeQTxU+eHVGgo/TpnauYo42RR5y1vTmLRZfY=,tag:syQfn1AmuA+vYhsPgMp2gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MjB0U1dlcEozQTJqNFcy
            Qk1VTlR5VytOUk5BemsrN2ZtS3A3ZVpiZjJFCjNlNDV4MXpZSlUvdzVPaHVMMjQ3
            cjVkV2dGbjgyNGh6Sm5ZZVR5cWhrSjgKLS0tIGU4OHRoNDhvZDdSVzVydVRoeTQ4
            L3VmR0dtazcvYUlRR0lnZER5bVAvZmsK1SSDWhoktVuHP9c3qV2/uzI0jIRF0qDd
            xEj75Yk/x9kUtVVoKoQpQHyVoKxhlWqDttxGWHb01FBGu/OuM9XV/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-20T09:57:27Z"
    mac: ENC[AES256_GCM,data:Cmtn0YWzVSRfjPbTe6a6R9YOX77JAenvAIz++eyRx5qAx6QVLvMvXTb8hUbpNlXCQCewAF8mmxQfOUuxBvusw2xYP3E48yyKMI4NFpKBVXRb8dVFd/n8TM0mC0N+Oi/LmZ1TBwm2MhbBWe3hMXYmSwO1bAYudGsNmMhKMwXTX1o=,iv:1/r3o4LrKNvSWikvhxxyyrFR/3ooPH8bjIjx7mNebdA=,tag:hEvoA9f/U8xEZMjsGLM0tQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
