apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:hvXZCpvU0IciR8eH5fkVtGDyVhZ7UaMPK7JDtjSqUmlIDFHx7XTXQ0Cbj6niPzKdclm6gidGdzopjeL+TJ+LMOt2WIybD5nBimbwaYFIueU4pdSMFJE0ohRF4sWCQpuAIVQGPnyOc0qGB/nEfJcBRMpvrdJQQolvX5AnydjIWBNMguUEJh/LVTPkD/xJN6a+RLnIcGFm+XXuy/s3XKJGgwjqXIE/+4z97eSIYjO87ba+/LoaxyKMCQ5WPATARxZ4YhzYr16dNu7j3xrzjgVR4LQ7eU+e4OGiOf3teA1iwzIiqW4tpdibz4dhh4Jw0ZnmEH7/kK2hP4frcS+r0LvtzwxK45jj4vv4NUc4bQ6j4y7rCwJEccOMSTpdhpCAc5rxb+7UDIFjzfVJB/oZvdTWxjZJn70E/yLE8i/Eb/aIvi8LWS1htILgplLYWeXC6SBBEMZnCmesAQmgxZPOMKEjBWiYD/QWv4WrnHcEkXvfTHY+FwYlhqJU0jZ5IaYtUQVhJZNUiMEswwsyaEFu/bl9OYhPD74q4OUD,iv:LrA7guouzjdGeUVfvO2a+VdPYIugUR8Ofz2qoDLFMBs=,tag:FtHXbfJLrOJ6hagh5tSEFw==,type:str]
    identity.pub: ENC[AES256_GCM,data:2lgamWcwT3IbS8dvhCIDYWepGS4OdkzdHps7HaalZql5Wk12M/qb/4VGzozLlM2AZ/26oK0YEf4opsAcmgLDiVOeRIDOidWQq/YEjnXeFCblWSmUVctVx5z594BWlHj/xmBLYyBmiHhZYLuV8aGeVni0Bx/Yfns6LJ+/3gNFjOFrq8XQJtLO3LoFmvuGlPWfwAOSniQqnfnT1y/ltYDSMeFZdCihaTa1m2/wNs22I+PRJETI1aqb/S/uk3sqAtTUntKORmw3ks7pc6/NEEagsoPQV3qMhXcjN+l0bF4I5s2L01Ds5kESEEQhXnwyhlqr2MLMTCl6B4GM22IM5XT4GggCkyg1kenMhGrFJg0jEKa1fgAE,iv:kRDYDUA7N0XmQrU5byjxzBBJbSGnuSaZ0qEbx2rW5NE=,tag:aB/QK/vR9Q3SYiniy2lxAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:F0SgUDAAkzYJqqn6yt9ecBWOET4WtlrYfqdGw8IQSXGZMdoDiyu4Nl8r8EiGiUT/FOvKdDJnI7wsOzmYRKWHPhyE6A/WY25r5xIza75XD9qzPtmhD/QqJRsMQb3Pa9c0rcVc3g+A1pbQeArUBx28sVY1rUMrXMDwByI8dXImzqUZk7ACrcNkn8MTicUgH2U+RfMQnRpJ2wdT0wwdzElCrdaECuVnOHMmojcfkVrjz4hwyGlolpe8LDAarRHKJDbsh00fwbei5ug9+ybLWBbUzJ7B0rSrusQH7O3XnEn2NaMOba3x,iv:ljY5TPXl03JFC2yxtBnXpRjaSuXw3Drl+Si8GAOrzjA=,tag:CbNwpey6xHOsmFIc1ZnfuA==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2022-12-26T21:53:17Z"
    name: flux-system
    namespace: flux-system
    resourceVersion: "2307"
    uid: 96f2dbcb-50d5-4724-a55e-872c6ddb2709
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZ3pZYTYvN09qUWEyU2Ew
            MTRSdGhvd09BeTNhUE1lQWprTmRMd3lpc3lNCktjYjF4bEE2OVNzcWJIcFo1QU0x
            ZXliNnVDNGhVSGMzS3c1cmdvTjZ6eVUKLS0tIG0wYzdZc3VRNmVzWCszRlN2dXZx
            YjB0R2lhNk9TMlJOVlR4dkJ4TmI0UXcKPBz+ydo4F9E2cwhh3VIeHZhPKmu+K6TN
            aO1wcXNFNraxMoymAWGyMNIMpsmpilzq+k7lyYyY69RjmcvhnN+hIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T22:03:33Z"
    mac: ENC[AES256_GCM,data:a52XyvnD3N0jRePaJH6i4VDXq3lwmHF6mdUFElssotkZV7bPOa0kqZwuPbOdeEsgbHsFXrP4f17nHPDAcUQ9A1QzA9VRyPuaanIiMJ9ZUKFkx+peIBFMjxL+HD4/kbxPFq5JteJPUAS7qJF8toxaRqawm+IJQQrCNJHejKx8s00=,iv:Fc5glKsi8viHQv/2+P9NfqRC7g+KZR1g3IbGWp6WHYw=,tag:mH3ZV9W7IqLMsPzp2Th1xQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
