---
# secret-values
adminPassword:
#
global:
  storageClass: openebs-zfspv-default
externalURL: https://harbor.lab.sipwork.pro
exposureType: ingress
service:
  type: LoadBalancer
  ports:
    http: 80
    https: 443
    notary: 4443
  annotations:
    metallb.universe.tf/address-pool: internal-pool
    metallb.universe.tf/loadBalancerIPs: 192.168.4.221
ingress:
  core:
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd,traefik-internal-ipwhitelist@kubernetescrd
    hostname: harbor.lab.sipwork.pro
    ingressClassName: traefik
    extraTls:
      - hosts:
          - harbor.lab.sipwork.pro
        secretName: lab.sipwork.pro-tls
  notary:
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd,traefik-internal-ipwhitelist@kubernetescrd
    hostname: notary.lab.sipwork.pro
    ingressClassName: traefik
    extraTls:
      - hosts:
          - notary.lab.sipwork.pro
        secretName: lab.sipwork.pro-tls
persistence:
  enabled: true
  s3:
# secret-values
    accesskey:
    secretkey:
#
    region: us-east-1
    regionendpoint: http://truenas.lab:9000
    bucket: harbor-registry
    encrypt: false
    secure: false
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
