adminPassword: ENC[AES256_GCM,data:kP8N0pWKl4GBxgcqWPiWJQ==,iv:AfTFy8n2zXCR+ysObtwFQy3f+JVfKDz5l6T800Pj1SU=,tag:xc0PRRpDqc8JKvC5WsjA3A==,type:str]
persistence:
    s3:
        accesskey: ENC[AES256_GCM,data:q++YzwAy,iv:hqWytkgPTfzNQ3ZXjJ3izymDy7CRL7tn88sklbePrsk=,tag:54uXUS+hpl7WHNK93fGxbA==,type:str]
        secretkey: ENC[AES256_GCM,data:Wr4hjQzcGTXPoVA4defFhQzRWpYH7teHotOSRtxk/TU=,iv:+jEKpPdJ0Bm6WRl/NrQYvqlxH6rqnmqN+MN/lB/4azM=,tag:6QD/wSN7N31r1YWtbZIUhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaGNPbWJ2cWQxZy9RanRX
            NUVyejZmWHFNM3ZUT1h5TWlXU1JhQmFoUzJ3Cjc4eHRWV1kxS0pjYmtUR1RHaEFw
            UE13ajJLM3JTUWR3dnBYdUtnZHhFUTQKLS0tIFRjTDBzNExPYWZyemM5eUgxdE5o
            NWdXbXMxcHZMajZFQld2RVZrd3oySWMKOhIefvpzOXGI5g7Qn/w4amBK5knnCIjI
            43VGQVNnUGD55tzsPsWFffb0R+qy9vbqI46FZ3+A570ISR1BkTWrcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T14:43:20Z"
    mac: ENC[AES256_GCM,data:Wti0+Ip14Yux2FSrOb5tNQleVeFBjaZ6KfaCT+OVaNsqtSBE4B0Fzaid3QOhUe/0R1A/UlB8pcOgC6y62mDC4163TDOQKGQaABrIO2RwCpBiPiRtMvWbw2MYaLXM7/eNHaCC86dWlitfKwuS43OholtG17eW7zW3f2HGYX+Bqgk=,iv:S8LOKc3zrzB8X3b0/ceFmKGpkPiyYhvor7X7WDChl9g=,tag:GHERN2atpU+88SWDTghJkg==,type:str]
    pgp: []
    encrypted_regex: .*
    version: 3.7.3
