adminPassword: ENC[AES256_GCM,data:WQllbGc1EAfWUrOWgjrbeA==,iv:+uD0BBW2aHaef6UC+uSp2IZ/WDh6hNo1g+WbyUil/+s=,tag:Z9Z1vv0zu0TfU2xeVvgLtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTTNUUjFGY3FZa0JRbDdr
            RnpyYVkvUlViQjFIcnpCazc2eVppMmNab2w0CklDeXFnQ3dLbmRqUjBwbVV1Lysz
            QUU4cHNHRUF5MGJUTFQ0RUMrMGg3N1kKLS0tIEhJblEzSEhDSm9YRnd6clVBd2Y5
            Nks4REtFejN5L3J0Q2xsOEw3WkRQMUEKn3scLHgyZADWskuOTx39m3goB98Hb7co
            dHN/OeQq0hEy5THxGhHrsrnVECAW8OibqnowXQlJZN7IT8IPUWt4YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T21:43:20Z"
    mac: ENC[AES256_GCM,data:gkLu8ilSsMOYL5IqHkzOAP+8p8aIiB5zjxpuCXSoOJ6qdm4A8rIa4BYy8odd0jLcDaVUNloZQFJ+0Y5CCCV10tSMF8et4xZG3kzPUn9HxB/LIkgUUJYv/QpGBKOM23lPIjYaso/m6bPqyyiNgJJKs5dJemAzwAzS/kCXwu1EI4U=,iv:5LO+wFTqiJDqI4hJjUNunK5+4rfagt9+b4J9KvlaDeg=,tag:GbaIb/rgwXw7PU2bXPFeSQ==,type:str]
    pgp: []
    encrypted_regex: ^(adminPassword)$
    version: 3.7.3
