---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: flux-system
spec:
  interval: 30m
  releaseName: mailu
  targetNamespace: tw
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: mailu
      version: 1.2.x
      sourceRef:
        kind: HelmRepository
        name: mailu-charts
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: mailu-values
      valuesKey: values-mailu.yaml
    - kind: Secret
      name: mailu-token
