---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-data
  namespace: tw
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
