---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../controllers/traefik.yaml
patches:
  - path: traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
