---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../controllers/kubed.yaml
  - ../../controllers/traefik.yaml
patches:
  - path: kubed-values.yaml
    target:
      kind: HelmRelease
      name: kubed
  - path: traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
