---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../configs/cluster-issuers.yaml
  - kube-dashboard.yaml
  - capacitor.yaml
  - multus.yaml
  - kubevirt-cr.yaml
  - cdi-cr.yaml
