---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: opnsense
  namespace: metallb-system
spec:
  myASN: 64500
  peerASN: 64501
  peerAddress: 192.168.4.1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.5.225-192.168.5.254
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.4.240-192.168.4.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pk8s-internal
  namespace: metallb-system
spec:
  ipAddressPools:
    - internal-pool
  interfaces:
    - eth0
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: pk8s-external
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#     - external-pool
#   interfaces:
#     - eth0.200
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-external
  namespace: metallb-system
spec:
  ipAddressPools:
    - external-pool
#  aggregationLength: 27
