---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-home
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "1.0.0",
      "name": "home",
      "plugins": [
        {
          "name": "vext",
          "type": "vlan",
          "master": "eth1",
          "vlanId": 110,
          "linkInContainer": false,
          "ipam": {
            "type": "whereabouts",
            "range": "192.168.1.200-192.168.1.216/24"
          }
        }
      ]
    }
