---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flexget-custom
  namespace: plex
data:
  subliminal: |
    #!/usr/bin/with-contenv bash
    pip install 'chardet<5.0.0'
    pip install subliminal
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flexget-configs
  namespace: plex
data:
  config.yml: |
    variables: variables.yml
    web_server:
      bind: 0.0.0.0
      port: 5050
      web_ui: yes
      base_url: /flexget

    templates:
      transmission-settings:
        _transmission: &transmission
          host: transmission.plex.svc.cluster.local
          port: 9091
          username: '{? transmission.username ?}'
          password: '{? transmission.password ?}'

    tasks:
      download-rss:
        rss: '{? rss.url ?}'
        # fetch all the feed series
        all_series: yes
        transmission:
          <<: *transmission

      move-shows:
        filesystem:
          path: /mnt/nas_public/transmission/complete
          regexp: '.*\.(avi|mkv|mp4)$'
          recursive: 4
        accept_all: yes
        seen: local
        # this is needed for the episode names
        thetvdb_lookup: yes
        all_series:
          # for some reason all_series rejects all episodes here, even with seen: local, so parse_only must be added
          parse_only: yes
        # TVDB doesn't recognise "Adventure Time with Finn and Jake" so you must add such exceptions here manually
        series: []
        copy:
          # this is where the series will be put
          to: /mnt/nas_public/series/{{ tvdb_series_name }}
          # save the file as "Series Name - SxxEyy - Episode Name.ext"
          rename: '{{ tvdb_series_name }} - {{ series_id }} - {{ tvdb_ep_name }}{{ location | pathext }}'
          along:
            subdirs:
              - Sub
              - Subs
              - subs
              - sub
              - Subs/
              - Sub/
              - Extra
              - Extras
            extensions:
              - srt
        list_add:
          - subtitle_list:
              list: subtitles
              check_subtitles: true
              remove_after: 14 days

      remove-stale-torrents:
        from_transmission:
          <<: *transmission
        disable: [seen, seen_info_hash]
        if:
          - transmission_progress == 100 and (transmission_date_done + timedelta(days=2)) < now: accept
        transmission:
          <<: *transmission
          action: purge

      subtitles-get:
        subtitle_list:
          list: subtitles
          check_subtitles: true
          remove_after: 14 days
          recursion_depth: 3
        list_match:
          from:
            - subtitle_list:
                list: subtitles
        no_entries_ok: yes
        subliminal:
          providers:
            - opensubtitles
          languages:
            - es
          alternatives:
            - en
          exact_match: no
          single: no
          authentication:
            opensubtitles:
              username: '{? subliminal.username ?}'
              password: '{? subliminal.password ?}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: flexget
  name: flexget
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flexget
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: flexget
    spec:
      containers:
        - env:
            - name: FG_LOG_FILE
              value: flexget.log
            - name: FG_LOG_LEVEL
              value: info
            - name: FG_WEBUI_PASSWD
              valueFrom:
                secretKeyRef:
                  name: flexget
                  key: FG_WEBUI_PASSWD
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Madrid
          image: linuxmaniac/flexget
          name: flexget
          ports:
            - containerPort: 5050
          resources: {}
          volumeMounts:
            - mountPath: /custom-cont-init.d
              name: flexget-custom
              readOnly: true
            - mountPath: /data
              name: flexget-data
            - mountPath: /config
              name: flexget-config
            - mountPath: /config/config.yml
              name: flexget-configs
              subPath: config.yml
            - mountPath: /config/variables.yml
              name: flexget-variables
              subPath: variables.yml
            - mountPath: /mnt/nas_public
              name: plex-media
      restartPolicy: Always
      volumes:
        - name: plex-media
          persistentVolumeClaim:
            claimName: plex-media
        - name: flexget-config
          persistentVolumeClaim:
            claimName: flexget-config
        - name: flexget-variables
          secret:
            secretName: flexget
        - name: flexget-configs
          configMap:
            name: flexget-configs
        - name: flexget-custom
          configMap:
            name: flexget-custom
        - name: flexget-data
          persistentVolumeClaim:
            claimName: flexget-data
