---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bazarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/bazarr
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bazarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bazarr
    namespace: flux-system
  policy:
    semver:
      range: '>=1.2.0'
