---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: bazarr
    namespace: plex
spec:
    image: lscr.io/linuxserver/bazarr
    interval: 12h
    exclusionList:
        - ^develop.*
        - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: bazarr
    namespace: plex
spec:
    imageRepositoryRef:
        name: bazarr
        namespace: plex
    policy:
        semver:
            range: '>=1.2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: sonarr
    namespace: plex
spec:
    image: lscr.io/linuxserver/sonarr
    interval: 12h
    exclusionList:
        - ^develop.*
        - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: sonarr
    namespace: plex
spec:
    imageRepositoryRef:
        name: sonarr
        namespace: plex
    policy:
        semver:
            range: '>=3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: radarr
    namespace: plex
spec:
    image: lscr.io/linuxserver/radarr
    interval: 12h
    exclusionList:
        - ^develop.*
        - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: radarr
    namespace: plex
spec:
    imageRepositoryRef:
        name: radarr
        namespace: plex
    policy:
        semver:
            range: '>=4.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: lidarr
    namespace: plex
spec:
    image: lscr.io/linuxserver/lidarr
    interval: 12h
    exclusionList:
        - ^develop.*
        - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: lidarr
    namespace: plex
spec:
    imageRepositoryRef:
        name: lidarr
        namespace: plex
    policy:
        semver:
            range: '>=1.3.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: prowlarr
    namespace: plex
spec:
    image: lscr.io/linuxserver/prowlarr
    interval: 12h
    exclusionList:
        - ^develop.*
        - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: prowlarr
    namespace: plex
spec:
    imageRepositoryRef:
        name: prowlarr
        namespace: plex
    policy:
        semver:
            range: '>=1.8.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: plex
    namespace: plex
spec:
    image: lscr.io/linuxserver/plex
    interval: 12h
    exclusionList:
        - ^develop.*
        - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: plex
    namespace: plex
spec:
    imageRepositoryRef:
        name: plex
        namespace: plex
    policy:
        semver:
            range: '>=1.32.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: transmission
    namespace: plex
spec:
    image: lscr.io/linuxserver/transmission
    interval: 12h
    exclusionList:
        - ^2021\..*
        - ^develop.*
        - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: transmission
    namespace: plex
spec:
    imageRepositoryRef:
        name: transmission
        namespace: plex
    policy:
        semver:
            range: '>=4.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: tautulli
    namespace: plex
spec:
    image: lscr.io/linuxserver/tautulli
    interval: 12h
    exclusionList:
        - ^2021\..*
        - ^develop.*
        - ^nightly-.*
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: tautulli
    namespace: plex
spec:
    imageRepositoryRef:
        name: tautulli
        namespace: plex
    policy:
        semver:
            range: '>=2.13.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
    name: plex
    namespace: plex
spec:
    interval: 30m
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    git:
        checkout:
            ref:
                branch: main
        commit:
            author:
                email: fluxcdbot@users.noreply.github.com
                name: fluxcdbot
            messageTemplate: |
                pk8s: [plex] Automated image update

                Automation name: {{ .AutomationObject }}

                Files:
                {{ range $filename, $_ := .Updated.Files -}}
                - {{ $filename }}
                {{ end -}}

                Objects:
                {{ range $resource, $_ := .Updated.Objects -}}
                - {{ $resource.Kind }} {{ $resource.Name }}
                {{ end -}}

                Images:
                {{ range .Updated.Images -}}
                - {{.}}
                {{ end -}}
        push:
            branch: flux-image-updates-plex
    update:
        path: ./apps/pk8s/plex
        strategy: Setters
