---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bazarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/bazarr
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bazarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bazarr
    namespace: flux-system
  policy:
    semver:
      range: '>=1.2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sonarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/sonarr
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sonarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sonarr
    namespace: flux-system
  policy:
    semver:
      range: '>=3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: radarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/radarr
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: radarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radarr
    namespace: flux-system
  policy:
    semver:
      range: '>=4.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lidarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/lidarr
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lidarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lidarr
    namespace: flux-system
  policy:
    semver:
      range: '>=1.3.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/prowlarr
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: prowlarr
    namespace: flux-system
  policy:
    semver:
      range: '>=1.8.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/plex
  interval: 12h
  exclusionList:
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: plex
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: plex
    namespace: flux-system
  policy:
    semver:
      range: '>=1.32.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: transmission
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/transmission
  interval: 12h
  exclusionList:
    - '^2021\..*'
    - '^develop.*'
    - '^nightly-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: transmission
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: transmission
    namespace: flux-system
  policy:
    semver:
      range: '>=4.0.0'
