---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: plex
  name: plex
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: plex
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: k3s-master
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: flexget
                  key: PLEX_CLAIM
            - name: PUID
              value: "1000"
            - name: VERSION
              value: docker
          image: lscr.io/linuxserver/plex:latest
          name: plex
          ports:
            - containerPort: 32400
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /tv
              name: plex-media
              subPath: series
            - mountPath: /movies
              name: plex-media
              subPath: films
            - mountPath: /music
              name: plex-media
              subPath: music
      hostNetwork: true
      restartPolicy: Always
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: plex-media
          persistentVolumeClaim:
            claimName: plex-media
