---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
  labels:
    org.democratic-csi.manual: plex-media
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: plex-media
    volumeAttributes:
      server: 192.168.10.13
      share: /mnt/main/media
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transmission-config
  labels:
    org.democratic-csi.manual: plex-transmission-config
spec:
  capacity:
    storage: 250Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-b535e738-f57c-4d34-825a-bba806aa1a38
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-b535e738-f57c-4d34-825a-bba806aa1a38-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-transmission-config
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-watch
  namespace: plex
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  labels:
    org.democratic-csi.manual: plex-config
spec:
  capacity:
    storage: 50Gi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-6d918b72-e34f-4f51-802e-51c997ef1ccc
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-6d918b72-e34f-4f51-802e-51c997ef1ccc-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-config
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-sonarr-config
  labels:
    org.democratic-csi.manual: plex-sonarr-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-4a9947b1-fcec-4bbb-b36b-346a05488b1f
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-4a9947b1-fcec-4bbb-b36b-346a05488b1f-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-sonarr-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-bazarr-config
  labels:
    org.democratic-csi.manual: plex-bazarr-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-5c282e80-0306-4872-b3a2-d7b78280313f
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-5c282e80-0306-4872-b3a2-d7b78280313f-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-bazarr-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-prowlarr-config
  labels:
    org.democratic-csi.manual: plex-prowlarr-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-157de7e5-7977-4492-a00f-bd33c5e4a114
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-157de7e5-7977-4492-a00f-bd33c5e4a114-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-prowlarr-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-radarr-config
  labels:
    org.democratic-csi.manual: plex-radarr-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-bfb1d154-5fdd-4f65-9268-cede7fde8714
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-bfb1d154-5fdd-4f65-9268-cede7fde8714-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-radarr-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-lidarr-config
  labels:
    org.democratic-csi.manual: plex-lidarr-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-c8722b04-e578-472a-8a2e-8300fa56ed21
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-c8722b04-e578-472a-8a2e-8300fa56ed21-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-lidarr-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tautulli-config
  labels:
    org.democratic-csi.manual: plex-tautulli-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-3167ebd6-e8e5-4e54-9718-be4638234c3b
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-3167ebd6-e8e5-4e54-9718-be4638234c3b-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-tautulli-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-mylar3-config
  labels:
    org.democratic-csi.manual: plex-mylar3-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-c784b6b9-deeb-4bfa-b893-2a2dc49851ed
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-c784b6b9-deeb-4bfa-b893-2a2dc49851ed-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylar3-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-mylar3-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-overseerr-config
  labels:
    org.democratic-csi.manual: plex-overseerr-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-fabc3f0f-9783-4d7b-bd17-17261fd353d1
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-fabc3f0f-9783-4d7b-bd17-17261fd353d1-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-overseerr-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-cleanuparr-config
  labels:
    org.democratic-csi.manual: plex-cleanuparr-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-422a90fa-8b2a-4f05-8fef-4abc77acc8c5
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-422a90fa-8b2a-4f05-8fef-4abc77acc8c5-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-cleanuparr-config
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-profilarr-config
  labels:
    org.democratic-csi.manual: plex-profilarr-config
spec:
  capacity:
    storage: 500Mi
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: pvc-4c28266b-4e91-4adb-8509-54cebb3ef67e
    fsType: ext4
    volumeAttributes:
      interface: ''
      iqn: >-
        iqn.2005-10.org.freenas.ctl:csi-pvc-4c28266b-4e91-4adb-8509-54cebb3ef67e-cluster
      lun: '0'
      node_attach_driver: iscsi
      portal: 192.168.4.5:3260
      portals: ''
      provisioner_driver: node-manual
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-democratic-csi
      namespace: democratic-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profilarr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      org.democratic-csi.manual: plex-profilarr-config
  resources:
    requests:
      storage: 500Mi
